binary_path: "/home/th/workspace/masters/simu/rtu-bin/"
frontend_path: "/home/th/workspace/masters/simu/cmd/service-station/frontend/"
network:
  address: "192.168.1.0/24"
  
rtus:
  - name: "pc1"
    address: "192.168.1.10"
  - name: "pc2"
    address: "192.168.1.20"

switches:
  - name: "sw1"
    address: ""
    connected:
      - to: "pc1"
  - name: "sw2"
    address: ""
    connected:
      - to: "pc2"
  - name: "sw3"
    address: ""
    connected:
      - to: "sw1"
      - to: "sw2"

